### ISSUE TITLE
Allow reporting annotations without creating a new check

### ISSUE THREAD

**Issue by nielsvanvelzen** [jwgmeligmeyling/checkstyle-github-action#5]
Right now this action adds a new check to report all annotations. Ideally I'd want to disable this behavior and just report annotations "normally" like other actions do.

For example, one of the linters I use is markdownlint and I enabled a problem matcher for that to create annotations. Another one is [yutailang0119/action-android-lint](https://github.com/yutailang0119/action-android-lint) that uses the GitHub actions toolkit to create the annotations from a Android XML file.

**Comment by jwgmeligmeyling** [comment]
Currently the Github API only allows pushing annotations by creating a new check run. I have asked Github to provide alternative APIs but as of now this cannot be done. More or less related to #2.

**Comment by nielsvanvelzen** [comment]
I took a better look at the android linter I mentioned and it simply said it prints the annotations to stdout via the command helper from the toolkit: https://github.com/actions/toolkit/blob/main/packages/core/src/command.ts

I'll see if I can make a PR for it later
